# Generated by Django 6.0 on 2025-12-13 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('NEWS', 'News Trader'), ('MM', 'Market Maker'), ('RND', 'Random Walker')], max_length=10)),
                ('risk_tolerance', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('trade_frequency', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
