# Generated by Django 6.0 on 2025-12-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('target_industry', models.CharField(choices=[('Technology', 'Tech'), ('Health', 'Health'), ('Finance', 'Finance'), ('Energy', 'Energy'), ('ConsumerGoods', 'Consgood'), ('GLOBAL', 'Global Market')], max_length=50)),
                ('sentiment_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
