# Generated by Django 6.0 on 2025-12-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ticker', models.SlugField()),
                ('industry', models.CharField(choices=[('Technology', 'Tech'), ('Health', 'Health'), ('Finance', 'Finance'), ('Energy', 'Energy'), ('ConsumerGoods', 'Consgood')], max_length=15)),
                ('spot_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('previous_close_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volume', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
